### ISSUE TITLE
Possible issue in tutorial 

### ISSUE THREAD

**Issue by SarahSorensen** [damianobaldan/riverconn#2]
Great package, thank you publishing it! I am really excited to use it.

While working through the tutorial at https://damianobaldan.github.io/riverconn_tutorial/#shapefile-slicing, the code gives me an issue when splitting the river network. I found that when it is building the data frame there is an error because the `length()` call is returning the number of columns, not the number of rows. Not sure if this is a version thing, but I updated it to `nrow` and wanted to let you know in case others have the same issue:
```
river_net_simplified <- lwgeom::st_split(shape_river_simple, network_links) %>%
  st_collection_extract(.,"LINESTRING") %>%
  data.frame(NodeID = 1:nrow(.), geometry = .) %>%
  st_as_sf() %>%
  mutate(length = st_length(.)) %>%
  st_join(., shape_river_small, join = st_is_within_distance, dist = 0.01 ) %>% 
  group_by(NodeID) %>%
  slice(which.max(UPLAND_SKM)) %>% 
  ungroup()
```

**Comment by damianobaldan** [comment]
The first two lines of code in the chunk `lwgeom::st_split(shape_river_simple, network_links) %>% sf::st_collection_extract(.,"LINESTRING")` produce an object of class `sfc_LINESTRING` not a data frame. Not sure using `nrow ` to give an unique id to all the elements in the collection works.

If the problem persists, please send me information on your session and a minimal reproducible example and I can dig into it.
