### ISSUE TITLE
SCI

### ISSUE THREAD

**Issue by zhaowentong** [damianobaldan/riverconn#3]
Hello ,I was looking at "A model to evaluate spatiotemporal variations of hydrological connectivity on a basin-scale complex river network After the article intensive human activity", there were some problems when trying to calculate the SCI index. According to the SCI formula, the weight of SCI index was based on river class and reach length. I used the following code to calculate the weight:

#calculate the weight , ORD_STRA is the river level for each reach
V(river_graph)$class <- V(river_graph)$ORD_STRA * V(river_graph)$length
#SCI
index_calculation(graph = river_graph,
weight = "class",
B_ij_flag = FALSE,
index_type = "reach",
index_mode = "from")
I am not sure if this calculation is correct and would be grateful for any advice.

**Comment by damianobaldan** [comment]
You are right your formulation has a problem. According to figure 3 of the paper you mention, each reach should be given a weight equal to the number of stream orders present in the region (subcatchment where the stream is). Once you have this information (should not be difficult to have it from a GIS environment) you can calculate the weight as:

 V(river_graph)$class <- (V(river_graph)$ORD_STRA)^0.5 * V(river_graph)$length

This way it mirrors the formula at paragraph 2.3.1.

**Comment by zhaowentong** [comment]
Thank you very much for your answer. Indeed, the number of river classes in the sub-basin should be used to calculate. Thank you very much for your answer.
















At 2023-04-11 19:17:11, "Damiano Baldan" ***@***.***> wrote:

You are right your formulation has a problem. According to figure 3 of the paper you mention, each reach should be given a weight equal to the number of stream orders present in the region (subcatchment where the stream is). Once you have this information (should not be difficult to have it from a GIS environment) you can calculate the weight as:

V(river_graph)$class <- (V(river_graph)$ORD_STRA)^0.5 * V(river_graph)$length

This way it mirrors the formula at paragraph 2.3.1.

**Comment by zhaowentong** [comment]
Hello, CAFI should be the accumulation of the upstream catchment area of the dam. I used "UPLAND_SKM" as the weight calculation. May I ask why "Joining with 'by = join_by(name)" appeared when I was calculating CAFI, and the result was NA? I would be grateful if you could give me some suggestions to solve this problem.The relevant calculation code is as follows:

> index[[1]] <- index_calculation(graph = river_graph,

+                                     weight = "UPLAND_SKM", 

+                                     dir_distance_type  = "symmetric",

+                                     index_type = "sum",

+                                     B_ij_flag = FALSE)

Joining with `by = join_by(name)`



















At 2023-04-11 22:03:57, "赵文通" ***@***.***> wrote:

Thank you very much for your answer. Indeed, the number of river classes in the sub-basin should be used to calculate. Thank you very much for your answer.
















At 2023-04-11 19:17:11, "Damiano Baldan" ***@***.***> wrote:

You are right your formulation has a problem. According to figure 3 of the paper you mention, each reach should be given a weight equal to the number of stream orders present in the region (subcatchment where the stream is). Once you have this information (should not be difficult to have it from a GIS environment) you can calculate the weight as:

V(river_graph)$class <- (V(river_graph)$ORD_STRA)^0.5 * V(river_graph)$length

This way it mirrors the formula at paragraph 2.3.1.

**Comment by damianobaldan** [comment]
It's hard to tell based on the information you provide. My guess is that
the attribute UPLAND_SKM is not an edge attribute in the graph you analyze
(I'd expect it to be a vertex attribute rather, based on the workflow). If
you send me a minimal reproducible example I can have a deeper look.

Il giorno sab 22 apr 2023 alle ore 10:12 zhaowentong <
***@***.***> ha scritto:

> Hello, CAFI should be the accumulation of the upstream catchment area of
> the dam. I used "UPLAND_SKM" as the weight calculation. May I ask why
> "Joining with 'by = join_by(name)" appeared when I was calculating CAFI,
> and the result was NA? I would be grateful if you could give me some
> suggestions to solve this problem.The relevant calculation code is as
> follows:
>
> > index[[1]] <- index_calculation(graph = river_graph,
>
> + weight = "UPLAND_SKM",
>
> + dir_distance_type = "symmetric",
>
> + index_type = "sum",
>
> + B_ij_flag = FALSE)
>
> Joining with `by = join_by(name)`
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>

**Comment by zhaowentong** [comment]
Dear Damiano Baldan,




I hope this email finds you well. I am reaching out to you regarding my recent computing example about CAFI, which I have attached for your reference.

I would greatly appreciate it if you could take a look and let me know if you see where I may have made an error. Your feedback would be extremely helpful to me, and I am very grateful for any insights you may have.

Thank you very much for your time and consideration. I look forward to hearing back from you soon.




Best regards,

zhaowentong




At 2023-04-24 15:21:32, "Damiano Baldan" ***@***.***> wrote:

It's hard to tell based on the information you provide. My guess is that
the attribute UPLAND_SKM is not an edge attribute in the graph you analyze
(I'd expect it to be a vertex attribute rather, based on the workflow). If
you send me a minimal reproducible example I can have a deeper look.

Il giorno sab 22 apr 2023 alle ore 10:12 zhaowentong <
***@***.***> ha scritto:

> Hello, CAFI should be the accumulation of the upstream catchment area of
> the dam. I used "UPLAND_SKM" as the weight calculation. May I ask why
> "Joining with 'by = join_by(name)" appeared when I was calculating CAFI,
> and the result was NA? I would be grateful if you could give me some
> suggestions to solve this problem.The relevant calculation code is as
> follows:
>
> > index[[1]] <- index_calculation(graph = river_graph,
>
> + weight = "UPLAND_SKM",
>
> + dir_distance_type = "symmetric",
>
> + index_type = "sum",
>
> + B_ij_flag = FALSE)
>
> Joining with `by = join_by(name)`
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>

**Comment by damianobaldan** [comment]
Hi, I can not find the attachment. Can you resend it to me?

**Comment by zhaowentong** [comment]
Sorry, I have uploaded my example to the attachment again, thank you!













At 2023-04-26 15:29:53, "Damiano Baldan" ***@***.***> wrote:

Hi, I can not find the attachment. Can you resend it to me?

**Comment by damianobaldan** [comment]
Hi there was a bug in the index_calculation function. The weight name was not properly identified in the edges dataframe used in the index calculation (g_e_df). I fixed it, try the newest version available on github (0.3.27). Thank you for reporting the issue!
Damiano

**Comment by zhaowentong** [comment]
Thank you for your modifications, now I can calculate the result. However, there is some discrepancy between the results calculated using riverconn and those calculated separately. The calculation of CAFI is the sum: the accumulation of upstream area / total basin area. I am skeptical about the results calculated using riverconn and wonder if there is a problem with my calculation code. I would like to use your developed riverconn to calculate the correct results, and I would appreciate any suggestions you may have.Using the code sent to you last time, the following results were calculated ,below is my calculation code.
#CAFI
index_calculation(graph = river_graph,
                   weight = "UPLAND_SKM", 
                   dir_distance_type  = "symmetric",
                   index_type = "sum",
                   B_ij_flag = FALSE)
#Joining with `by = join_by(name)`
#[1] 0.02032115
> sum(shape_stations$UPLAND_SKM/shape_basin$UP_AREA)
#[1] 0.1856972
